<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    '1260b8c06eae33119b0e81cefb1c9a88' => $vendorDir . '/yahnis-elsts/plugin-update-checker/load-v5p6.php',
);
