<?php

// autoload_static.php @generated by Composer

namespace Ppfeufer\Plugin\DownloadButtonShortcode\Libs\Composer\Autoload;

class ComposerStaticInitc904d0169dfc2400ea96e3e27d57cbe8
{
    public static $files = array (
        '1260b8c06eae33119b0e81cefb1c9a88' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/load-v5p6.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Ppfeufer\\Plugin\\DownloadButtonShortcode\\' => 40,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/Sources',
        ),
    );

    public static $classMap = array (
        'ComposerAutoloaderInitc904d0169dfc2400ea96e3e27d57cbe8' => __DIR__ . '/..' . '/composer/autoload_real.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Parsedown' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/vendor/ParsedownModern.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\Composer\\Autoload\\ClassLoader' => __DIR__ . '/..' . '/composer/ClassLoader.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\Composer\\Autoload\\ComposerStaticInitc904d0169dfc2400ea96e3e27d57cbe8' => __DIR__ . '/..' . '/composer/autoload_static.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Autoloader' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Autoloader.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\DebugBar\\Extension' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/DebugBar/Extension.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\DebugBar\\Panel' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/DebugBar/Panel.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\DebugBar\\PluginExtension' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/DebugBar/PluginExtension.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\DebugBar\\PluginPanel' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/DebugBar/PluginPanel.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\DebugBar\\ThemePanel' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/DebugBar/ThemePanel.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\InstalledPackage' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/InstalledPackage.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Metadata' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Metadata.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\OAuthSignature' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/OAuthSignature.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Plugin\\Package' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Plugin/Package.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Plugin\\PluginInfo' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Plugin/PluginInfo.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Plugin\\Ui' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Plugin/Ui.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Plugin\\Update' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Plugin/Update.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Plugin\\UpdateChecker' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Plugin/UpdateChecker.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\PucFactory' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/PucFactory.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Scheduler' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Scheduler.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\StateStore' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/StateStore.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Theme\\Package' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Theme/Package.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Theme\\Update' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Theme/Update.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Theme\\UpdateChecker' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Theme/UpdateChecker.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Update' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Update.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\UpdateChecker' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/UpdateChecker.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\UpgraderStatus' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/UpgraderStatus.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Utils' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Utils.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\Api' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/Api.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\BaseChecker' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/BaseChecker.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\BitBucketApi' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/BitBucketApi.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\GitHubApi' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/GitHubApi.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\GitLabApi' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/GitLabApi.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\PluginUpdateChecker' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/PluginUpdateChecker.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\Reference' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/Reference.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\ReleaseAssetSupport' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/ReleaseAssetSupport.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\ReleaseFilteringFeature' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/ReleaseFilteringFeature.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\ThemeUpdateChecker' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/ThemeUpdateChecker.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\Vcs\\VcsCheckerMethods' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/Vcs/VcsCheckerMethods.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Libs\\YahnisElsts\\PluginUpdateChecker\\v5p6\\WpCliCheckTrigger' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5p6/WpCliCheckTrigger.php',
        'Ppfeufer\\Plugin\\DownloadButtonShortcode\\Main' => __DIR__ . '/../../..' . '/Sources/Main.php',
        'PucReadmeParser' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/vendor/PucReadmeParser.php',
        'YahnisElsts\\PluginUpdateChecker\\v5\\PucFactory' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/Puc/v5/PucFactory.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc904d0169dfc2400ea96e3e27d57cbe8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc904d0169dfc2400ea96e3e27d57cbe8::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc904d0169dfc2400ea96e3e27d57cbe8::$classMap;

        }, null, ClassLoader::class);
    }
}
